# -*- coding: utf-8 -*-
"""
zh_dict.py — StrykerOSS 简体中文翻译词典

格式: name -> 中文文案。占位符 (%1$s, %d, %s, \n 等) 必须与英文原文一致，
由 localize_zh.py 直接写入 values-zh-rCN/strings*.xml。
"""
# flake8: noqa
TRANSLATIONS = {
    "app_name": "StrykerOSS",
    "install": "安装",
    "install2": "核心加载中",
    "install3": "正在安装核心",
    "fail": "下载失败，请检查网络连接",
    "install_unpack": "正在解压核心",
    "local_scan": "扫描本地网络可能需要一些时间，但结果会非常棒 💣！",
    "no_results": "未找到结果",
    "ew_welcome": "欢迎使用添加漏洞利用向导，请按照所有说明和步骤操作以成功添加。点击“继续”按钮进入下一步。",
    "ew_path": "(/sdcard/Stryker/exploits/)",
    "select": "漏洞利用脚本路径：点击选择",
    "no_pattern": "注意，应用在文件中找不到这样的行。这可能是脚本的特性或混淆导致的。你确定输入正确吗？",
    "warn": "警告",
    "yes": "是",
    "no": "否",
    "exploits": "在漏洞利用模块中，你可以添加自己的漏洞利用和脚本，然后按预期使用。支持自动参数检测",
    "scanners": "在这里你可以创建或编辑现成的漏洞扫描器。你可以组合协议漏洞利用实现一键启动。",
    "exploits_title": "漏洞利用",
    "scanners_title": "扫描器",
    "tutorials": "教程",
    "add": "添加",
    "run": "运行",
    "exs": "漏洞利用…",
    "usb": "USB 设备已连接",
    "customvalue": "输入自定义值",
    "wifi": "WiFi 网络",
    "dashboard": "首页",
    "wifi_networks": "WiFi 网络",
    "local_network": "本地网络",
    "handshakes": "握手包",
    "exploit_hub": "漏洞利用",
    "core_manager": "管理器",
    "check_camera": "检查 RTSP 摄像头漏洞",
    "run_custom": "运行自定义漏洞利用",
    "nmap": "Nmap 扫描器",
    "scanning_wifi": "正在扫描 Wi-Fi 网络",
    "delcache": "正在清除缓存…",
    "download_apk": "正在加载应用…",
    "download_chroot": "正在加载 chroot…",
    "unmount": "正在卸载核心…",
    "delchroot": "正在移除旧 chroot…",
    "installchroot": "正在安装新的 chroot",
    "installapk": "请安装所请求的 APK！",
    "failed_try": "失败了，再试一次！",
    "get_exploitfile": "从文件中选择脚本",
    "path": "路径：",
    "please_file": "请选择一个文件！",
    "pass_founded": "找到密码：",
    "select_word": "选择字典",
    "pass_not_found": "未找到密码",
    "error_upload": "文件上传错误！",
    "file_was_uploaded": "该文件之前已经上传过！",
    "upload_success": "文件上传成功，请查收邮件！",
    "please_connect": "请先连接网络！",
    "stop": "停止",
    "start": "开始",
    "scan_finised": "扫描完成！",
    "scan_finished_desc": "扫描完成！你可以使用顶部的图标保存结果！",
    "save": "保存",
    "vnc_install_stage_refresh": "刷新软件包索引",
    "vnc_install_stage_packages": "安装 XFCE 和 x11vnc",
    "vnc_install_stage_password": "准备 VNC 密码",
    "vnc_install_stage_scripts": "写入辅助脚本",
    "vnc_install_stage_verify": "验证安装",
    "vnc_section_stages": "安装步骤",
    "vnc_section_log": "安装输出",
    "vm_disk_auto": "自动",
    "vm_disk_auto_msg": "虚拟机磁盘没有固定大小。当前包含 %1$s 真实数据，位于 %2$s 镜像中，每次启动时会扩展以覆盖手机剩余 %3$s 空间。\n\n仅在客户机写入时消耗存储空间，虚拟机内释放的空间会在下次启动时返还给手机。",
    "local_vendor_unknown": "未知厂商",
    "coose_port": "选择端口",
    "saved_to_exp": "已保存到漏洞利用库！",
    "trying": "正在尝试：",
    "succes": "成功！",
    "cant_find_netw": "抱歉，找不到该网络。下拉重试",
    "select_word2": "选择字典",
    "pass": "密码：",
    "not_vuln_pixie": "网络不存在漏洞或信号太弱",
    "plata": "主板：",
    "pick": "选择接口",
    "exploit_wizard": "漏洞利用向导",
    "exploit_wizard_step_1_of_2": "漏洞利用向导（步骤 1/2）",
    "arguments": "参数",
    "allowed_shortcuts_n_ip_ip_address_n_port_port_n_gw_gateway_n_mask_subnet_mask_n_mac_mac_address_n_ncustom_shortcuts_n_customtext_app_will_ask_you_to_enter_variable_manually": "允许的快捷方式：\n{IP} - IP 地址\n{PORT} - 端口\n{GW} - 网关\n{MASK} - 子网掩码\n{MAC} - MAC 地址\n\n自定义快捷方式：\n{CUSTOMTEXT} - 应用会要求你手动输入变量",
    "example_n_myexploit_t_ip_p_port_threads_n_n_n_n_works_as_customtext_and_you_will_be_able_to_enter_it_before_scan_starts": "示例：\n./myexploit -t {IP} -p {PORT} --threads {N}\n\n{N} 的作用与 {CUSTOMTEXT} 相同，扫描开始前你可以输入它！",
    "exploit_wizard_step_2_of_2": "漏洞利用向导（步骤 2/2）",
    "title": "标题",
    "successful_pattern": "成功匹配模式",
    "how_it_works_nenter_message_or_part_of_it_which_script_displays_on_success_result_if_no_msg_found_result_marked_as_failed": "它是如何工作的？\n输入脚本在成功时会显示的消息（或其一部分）。如果未找到该消息，则结果标记为失败！",
    "example_n_exploit_successful_marked_as_good_result_nif_no_such_msg_failed": "示例：\n[vuln] Target vulnreable - 标记为成功结果。\n如果没有这样的消息，则为错误",
    "error_mount": "挂载错误！请确保存在 Stryker 文件夹！",
    "exploit_list": "漏洞利用列表",
    "enter_mac": "输入 MAC 地址",
    "captured_be_here": "捕获的握手包会显示在这里！",
    "detect_os": "检测操作系统",
    "detect_services": "服务发现",
    "fast_scan_less_ports": "快速扫描（较少端口）",
    "mark_host_s_as_online": "标记主机在线",
    "set_ranges": "设置范围",
    "ranges_and_ips": "范围与 IP",
    "set_max_threads": "设置最大线程数",
    "set_timeout_ms": "设置超时（毫秒）",
    "initializing": "初始化…",
    "q": "输入请求",
    "enter_pin": "输入 PIN",
    "cancel": "取消",
    "auto_connect": "自动连接",
    "not_vuln_local": "抱歉，目标不存在漏洞",
    "vuln_for": "目标存在的漏洞：",
    "choose_opt": "选择选项",
    "cut_dev": "断开设备",
    "perm_cut": "永久断开",
    "cut20": "断开 20 秒",
    "piin": "\nPIN：",
    "website": "Web\n扫描器",
    "try_again": "重试",
    "userhello": "👋 欢迎回来，",
    "ip_ranges": "IP 范围",
    "ports": "端口",
    "fill_rs": "请填写所有字段！",
    "magisk_off_success": "成功！",
    "magisk_notif_bad": "失败",
    "open_link_error": "没有已安装的应用可以打开此链接。",
    "permissions_is_not_granted": "未授予权限！",
    "permissions_check_again": "重新检查权限。",
    "device_is_not_supported": "你的设备不受支持。",
    "support_only_64bit": "Stryker 仅支持 64 位设备。不要使用 🦖！",
    "notification_channel_updater": "更新器",
    "downloading_core": "正在下载核心...",
    "installing_core": "正在安装核心...",
    "installing": "正在安装...",
    "loading": "正在加载...",
    "next": "下一步",
    "not": "❌",
    "done": "完成",
    "unhandled_exception": "发生未处理的异常！",
    "are_you_sure": "你确定吗？",
    "remove_module_dialog_description": "这将删除与以下内容相关的所有文件和数据",
    "credentials": "凭据",
    "copied_to_clipboard": "已复制到剪贴板。",
    "clear": "清除",
    "copy": "复制",
    "help": "帮助",
    "active_clients": "活跃客户端：",
    "active_clients_not_found": "未找到活跃客户端。",
    "error": "错误",
    "ok": "确定",
    "settings_title": "设置",
    "settings_subtitle": "自定义 Stryker 以匹配你的工作流程",
    "settings_section_wifi": "WiFi",
    "settings_section_local": "本地网络",
    "settings_section_privacy": "隐私",
    "settings_section_system": "系统",
    "settings_autowifi_title": "自动开启 WiFi",
    "settings_autowifi_subtitle": "攻击完成后自动重新打开 Android WiFi",
    "settings_save_aps_title": "保存破解的凭据",
    "settings_save_aps_subtitle": "将恢复的 PSK 和 PIN 存储在加密历史记录中",
    "settings_change_interfaces_title": "网络接口",
    "settings_change_interfaces_subtitle": "选择哪个适配器负责扫描、握手、deauth、WPS",
    "settings_pixie_iface_down_title": "关闭接口",
    "settings_pixie_iface_down_subtitle": "在 Pixie/WPS 攻击期间禁用 Wi-Fi 并关闭适配器。大多数内置适配器需要此项；使用必须保持开启的外部适配器时请关闭",
    "settings_change_commands_title": "自定义监控命令",
    "settings_change_commands_subtitle": "覆盖每个适配器启用监控模式的方式",
    "settings_autoscan_title": "自动端口扫描",
    "settings_autoscan_subtitle": "对每个发现的主机运行 Nmap 端口扫描",
    "settings_banner_title": "服务横幅检测",
    "settings_banner_subtitle": "向 Nmap 追加 --script=banner（更慢，更详细）",
    "settings_max_par_title": "最大并行扫描数",
    "settings_max_par_subtitle": "同时扫描多少台主机",
    "settings_max_par_dialog_title": "最大并行扫描数",
    "settings_max_par_dialog_hint": "数字（建议 < 10）",
    "settings_max_par_dialog_error": "请输入大于零的数字",
    "settings_hide_title": "隐藏 MAC 地址",
    "settings_hide_subtitle": "在对话框和截图中打码 MAC",
    "settings_logs_title": "显示调试日志",
    "settings_logs_subtitle": "打开应用内日志查看器",
    "settings_unmount_title": "卸载 chroot",
    "settings_unmount_subtitle": "分离 Stryker 环境并关闭应用",
    "settings_unmount_confirm_title": "卸载 chroot？",
    "settings_unmount_confirm_message": "Stryker 将关闭。下次启动时会重新挂载 chroot 环境。",
    "settings_unmount_success": "卸载成功",
    "settings_unmount_failed": "卸载失败——可能有进程仍在占用",
    "settings_delete_title": "删除 Stryker",
    "settings_delete_subtitle": "清除 chroot 并卸载应用",
    "settings_delete_confirm_title": "删除 Stryker？",
    "settings_delete_confirm_message": "你的所有数据、已保存的网络、漏洞利用和设置都将被清除。此操作无法撤销。",
    "settings_delete_goodbye": "很抱歉给你带来了糟糕的体验——下次我们会做得更好 :)",
    "settings_delete_unmount_failed": "无法卸载 chroot——为保护你的数据安全，拒绝删除",
    "dashboard_hello": "欢迎回来",
    "dashboard_subtitle_default": "点击工具开始使用",
    "dashboard_subtitle_stats": "已保存 %1$d 个 · 上次扫描发现 %2$d 台设备",
    "dashboard_section_tools": "工具",
    "dashboard_section_recent": "最近活动",
    "dashboard_section_utilities": "实用工具",
    "dashboard_tile_handshakes": "握手包",
    "dashboard_tile_exploits": "漏洞利用\n中心",
    "dashboard_tile_searchsploit": "漏洞利用\n数据库",
    "dashboard_tile_geomac": "GeoMac",
    "dashboard_tile_metasploit": "Metasploit",
    "dashboard_card_terminal_title": "打开终端",
    "dashboard_card_terminal_subtitle": "进入 Stryker chroot shell",
    "dashboard_card_news_title": "新闻",
    "dashboard_card_news_subtitle": "项目更新与变更日志",
    "dashboard_card_saved_title": "已保存的网络",
    "dashboard_card_saved_subtitle": "你恢复的密码和 PIN",
    "dashboard_card_recentscan_title": "最近一次本地扫描",
    "dashboard_card_recentscan_subtitle": "打开最近的设备列表",
    "dashboard_card_recentscan_empty": "还没有扫描记录——请先运行本地网络扫描",
    "dashboard_magisk_title": "Magisk root 提示",
    "dashboard_magisk_body": "Stryker 会频繁使用 root——Magisk 通知很快就会变得烦人。要我们静音它们吗？",
    "dashboard_magisk_dismiss": "忽略",
    "dashboard_magisk_silence": "静音",
    "cmd_hint": "在命令中使用 $ifc 表示接口名，$ch 表示信道",
    "cmd_add_device": "添加 USB 设备",
    "cmd_dialog_add_title": "添加新设备",
    "cmd_dialog_edit_title": "编辑设备",
    "cmd_select_interface": "选择接口",
    "cmd_enable_command": "启用命令",
    "cmd_disable_command": "禁用命令",
    "cmd_select_device": "选择设备",
    "cmd_cancel": "取消",
    "cmd_save": "保存",
    "cmd_add": "添加",
    "cmd_error_no_wlan0": "只能修改 Wlan0。你不能添加它。",
    "cmd_error_fill_all": "请填写所有字段。",
    "settings_iface_scan_title": "扫描接口",
    "settings_iface_scan_desc": "用于 WiFi 发现和除握手捕获与 deauth 外的所有攻击",
    "settings_iface_hs_title": "握手接口",
    "settings_iface_hs_desc": "用于监控模式和握手捕获",
    "settings_iface_deauth_title": "Deauth 接口",
    "settings_iface_deauth_desc": "用于将客户端踢出接入点",
    "settings_iface_wps_title": "WPS 接口",
    "settings_iface_wps_desc": "用于所有 WPS 攻击（Pixie、测试 PIN、常见 PIN、暴力破解）",
    "arsenal_title": "武器库",
    "arsenal_drawer_title": "武器库",
    "arsenal_tab_hub": "我的集散地",
    "arsenal_tab_db": "数据库",
    "arsenal_subtitle_loading": "正在加载你的装备…",
    "arsenal_subtitle_format": "%1$d 个漏洞利用 · ExploitDB %2$s",
    "arsenal_subtitle_db_ready": "就绪",
    "arsenal_subtitle_db_missing": "未安装",
    "arsenal_hub_section": "活跃装备",
    "arsenal_hub_empty_title": "你的集散地为空",
    "arsenal_hub_empty_body": "添加自定义脚本或从 ExploitDB 标签页获取一个。",
    "arsenal_hub_add": "新建漏洞利用",
    "arsenal_hub_badge_system": "内置",
    "arsenal_add_title": "添加到集散地",
    "arsenal_add_subtitle": "选择一个脚本，给它起个名字，可选填成功匹配模式。",
    "arsenal_add_step_file": "源文件",
    "arsenal_add_file_placeholder": "选择文件",
    "arsenal_add_file_hint": "位于 /sdcard/Stryker/exploits 下",
    "arsenal_add_field_title": "漏洞利用名称",
    "arsenal_add_field_args": "参数",
    "arsenal_add_field_args_hint": "使用 {IP}、{PORT}、{MAC}、{GW}、{MASK} 或任意自定义 {VAR}——启动前武器库会要求输入值。",
    "arsenal_add_field_success": "成功模式",
    "arsenal_add_field_success_hint": "漏洞利用成功时打印的子串。留空 = 始终视为成功。",
    "arsenal_add_pick_file_title": "选择脚本",
    "arsenal_add_no_files": "/sdcard/Stryker/exploits 中没有文件——请先复制一个进去。",
    "arsenal_add_file_required": "请先选择脚本。",
    "arsenal_add_title_required": "请给它起个名字。",
    "arsenal_add_no_pattern_title": "无成功模式",
    "arsenal_add_no_pattern_body": "没有成功模式时，每次运行都会被标记为成功。仍然保存吗？",
    "arsenal_add_saved": "已将 %1$s 保存到你的集散地",
    "arsenal_run_command": "启动命令",
    "arsenal_run_variables": "填写变量",
    "arsenal_run_copy": "复制",
    "arsenal_run_launch": "启动",
    "arsenal_run_copied": "命令已复制到剪贴板",
    "arsenal_run_launched": "漏洞利用正在后台运行",
    "arsenal_run_fill_vars": "启动前请填写所有 {variables}。",
    "arsenal_run_delete": "从集散地移除",
    "arsenal_run_delete_confirm_title": "从集散地移除？",
    "arsenal_run_delete_confirm_body": "从你的集散地移除 %1$s？文件仍保留在 /sdcard/Stryker/exploits 中。",
    "arsenal_db_search_hint": "搜索 ExploitDB（例如 eternalblue）",
    "arsenal_db_search_required": "请输入查询词。",
    "arsenal_db_hint_title": "搜索 ExploitDB",
    "arsenal_db_hint_body": "输入关键字、CVE 或产品名称。",
    "arsenal_db_no_results_title": "无结果",
    "arsenal_db_no_results_body": "没有匹配 \"%1$s\" 的漏洞利用。",
    "arsenal_db_status_title": "离线镜像就绪",
    "arsenal_db_status_ready": "就绪",
    "arsenal_db_status_count": "%1$s 个漏洞利用",
    "arsenal_db_suggestions_title": "热门搜索",
    "arsenal_db_tips_title": "搜索技巧",
    "arsenal_db_tips_body": "词之间是 AND 匹配。尝试用 CVE 编号直接查找。添加平台名称（linux、windows）以缩小结果范围。",
    "arsenal_db_install_title": "ExploitDB 未安装",
    "arsenal_db_install_subtitle": "点击安装以克隆 searchsploit 镜像",
    "arsenal_db_install_button": "安装 ExploitDB",
    "arsenal_db_install_running": "正在安装…请保持此屏幕打开",
    "arsenal_db_install_cloning": "正在克隆 ExploitDB——这是最慢的部分",
    "arsenal_db_install_verifying": "正在验证安装",
    "arsenal_db_install_done": "安装完成",
    "arsenal_db_install_failed": "安装失败——请查看上方日志",
    "arsenal_db_install_note": "首次安装克隆约 200 MB。之后的搜索均为离线。",
    "arsenal_db_field_platform": "平台",
    "arsenal_db_field_type": "类型",
    "arsenal_db_field_author": "作者",
    "arsenal_db_field_date": "发布日期",
    "arsenal_db_field_path": "路径",
    "arsenal_db_view_source": "查看源码",
    "arsenal_db_save_file": "保存文件",
    "arsenal_db_add_to_hub": "添加到集散地",
    "arsenal_db_missing_path": "此条目没有路径。",
    "arsenal_db_missing_id": "此条目没有 EDB-ID。",
    "arsenal_db_copying": "正在复制脚本到 /sdcard/Stryker/exploits…",
    "arsenal_db_saved_file": "已保存到 /sdcard/Stryker/exploits",
    "arsenal_db_added_to_hub": "已添加到集散地",
    "arsenal_run_batch_title": "漏洞利用集散地",
    "arsenal_run_batch_starting": "正在准备…",
    "arsenal_run_batch_testing": "正在测试 %1$s",
    "arsenal_run_batch_summary_running": "正在运行 %1$d / %2$d 个漏洞利用",
    "arsenal_run_batch_vuln": "目标存在的漏洞：%1$s",
    "arsenal_run_batch_done": "完成",
    "arsenal_run_batch_close": "关闭",

    "local_title": "本地网络",
    "local_subtitle_idle": "发现你周围的设备",
    "local_subtitle_scanning": "正在扫描网络…",
    "local_subtitle_no_wifi": "未连接 Wi-Fi",
    "local_section_network": "网络",
    "local_section_devices": "发现的设备",
    "local_section_actions": "快捷操作",
    "local_section_ports": "开放端口",
    "local_section_attacks": "工具与攻击",
    "local_status_connected": "已连接",
    "local_status_offline": "离线",
    "local_status_scanning": "扫描中",
    "local_status_done": "就绪",
    "local_chip_devices": "%1$d 台设备",
    "local_chip_scanning": "扫描中…",
    "local_gateway_label": "网关",
    "local_mask_label": "子网",
    "local_ssid_label": "SSID",
    "local_empty_title": "尚未发现设备",
    "local_empty_body": "下拉重新扫描，或确认你已连接 Wi-Fi。",
    "local_no_wifi_title": "Wi-Fi 已断开",
    "local_no_wifi_body": "请连接 Wi-Fi 网络以发现本地主机。",
    "local_firewall_warn": "检测到防火墙——开放端口可能被过滤。漏洞检测可能不可靠。",
    "local_action_rescan": "重新扫描",
    "local_action_stop": "停止",
    "local_card_ports": "%1$d 个端口",
    "local_card_no_ports": "无开放端口",
    "local_card_router": "网关",
    "local_card_cut": "已断开",
    "local_device_os_unknown": "未知操作系统",
    "local_device_mac_label": "MAC 地址",
    "local_device_ip_label": "IP 地址",
    "local_device_vendor_label": "厂商",
    "local_device_os_label": "操作系统",
    "local_action_open_http": "打开 HTTP",
    "local_action_open_https": "打开 HTTPS",
    "local_action_open_ftp": "打开 FTP",
    "local_action_open_ssh": "打开 SSH",
    "local_action_nmap_report": "详细 Nmap 报告",
    "local_action_nmap_report_sub": "生成可分享的扫描摘要",
    "local_action_vulns": "检查已知漏洞",
    "local_action_vulns_sub": "EternalBlue、SMBGhost、BlueKeep、CVE-2022-27255",
    "local_action_netcut": "切断互联网访问",
    "local_action_netcut_sub": "ARP 欺骗选项",
    "local_action_hydra": "暴力破解凭据",
    "local_action_hydra_sub": "针对任意服务的 THC-Hydra",
    "local_action_camera": "检查 RTSP 摄像头",
    "local_action_camera_sub": "Cameradar 默认凭据扫描",
    "local_action_admin": "探测管理后台",
    "local_action_admin_sub": "尝试路由器默认凭据",
    "local_action_msf": "启动 Metasploit",
    "local_action_msf_sub": "打开 MSF 控制台",
    "local_action_payload": "生成载荷",
    "local_action_payload_sub": "msfvenom 封装",
    "local_action_wol": "网络唤醒",
    "local_action_wol_sub": "发送魔术包",
    "local_action_run_exploit": "运行自定义漏洞利用",
    "local_action_run_exploit_sub": "从你的集散地中选择一个",
    "local_ports_title": "开放端口",
    "local_ports_count": "%1$d 个开放",
    "local_ports_empty": "此主机没有开放端口",
    "local_ports_show_raw": "显示原始 nmap 输出",
    "local_ports_show_list": "显示端口列表",
    "local_netcut_choose": "选择操作",
    "local_netcut_restore": "恢复连接",
    "local_netcut_confirm_all_title": "断开所有设备？",
    "local_netcut_confirm_all_body": "这将阻止局域网上的所有设备访问网关。",
    "local_netcut_restore_all_title": "恢复所有设备？",
    "local_netcut_restore_all_body": "重新启用局域网上所有设备的互联网访问。",
    "local_wol_sent": "已发送 Wake-on-LAN 数据包",
    "local_wait_scan": "请等待该主机的扫描完成",
    "local_scan_target_title": "扫描目标",
    "local_scan_target_body": "覆盖 nmap 扫描的网关和子网。留空则从当前 Wi-Fi 连接自动检测。",
    "local_scan_target_gateway_hint": "网关 IP（例如 192.168.1.1）",
    "local_scan_target_cidr_hint": "CIDR 掩码（1–32）",
    "local_scan_target_apply": "应用并重新扫描",
    "local_scan_target_auto": "使用自动检测",
    "local_scan_target_invalid_ip": "请输入有效的 IPv4 地址",
    "local_scan_target_invalid_cidr": "请输入 1 到 32 之间的 CIDR 掩码",
    "local_scan_target_custom_label": "自定义",
    "wifi_title": "Wi-Fi 网络",
    "wifi_subtitle_scanning": "正在扫描无线电波…",
    "wifi_subtitle_done": "发现 %1$d 个网络",
    "wifi_subtitle_none": "尚未捕获到网络",
    "wifi_section_status": "适配器",
    "wifi_section_networks": "发现的网络",
    "wifi_interface_label": "接口",
    "wifi_channel_label": "信道",
    "wifi_band_label": "频段",
    "wifi_status_scanning": "扫描中",
    "wifi_status_ready": "就绪",
    "wifi_status_failed": "扫描失败",
    "wifi_empty_title": "未找到网络",
    "wifi_empty_body": "下拉或点击重试重新扫描。为确保最佳效果，请确认你的适配器支持监控模式。",
    "wifi_retry": "重试",
    "wifi_chip_wps": "WPS",
    "wifi_chip_lock": "锁定",
    "wifi_chip_pixie": "PIXIE",
    "wifi_chip_pixie_verified": "PIXIE ✓",
    "wifi_chip_key": "密钥",
    "wifi_chip_5g": "5 GHz",
    "wifi_signal_label": "%1$d%%",
    "wifi_signal_chip_label": "信号",
    "wifi_card_model": "型号：%1$s",
    "wifi_card_unknown_vendor": "未知厂商",
    "wifi_fab_pixie": "自动 Pixie Dust",
    "wifi_fab_hs": "批量握手捕获",
    "wifi_fab_deauth": "批量解除认证",
    "nmap_title": "Nmap 扫描器",
    "nmap_subtitle_idle": "探测主机、识别服务、映射开放端口。",
    "nmap_subtitle_running": "正在运行扫描…",
    "nmap_subtitle_done": "扫描完成",
    "nmap_section_target": "目标",
    "nmap_section_profile": "方案",
    "nmap_section_options": "选项",
    "nmap_section_output": "输出",
    "nmap_target_hint": "主机、IP 或 CIDR（例如 192.168.1.0/24）",
    "nmap_target_empty": "输入目标以开始扫描",
    "nmap_target_invalid": "目标格式无效",
    "nmap_target_recent": "最近目标",
    "nmap_target_clear": "清空字段",
    "nmap_btn_start": "开始扫描",
    "nmap_btn_stop": "停止扫描",
    "nmap_btn_save": "保存输出",
    "nmap_btn_share": "分享输出",
    "nmap_btn_copy": "复制到剪贴板",
    "nmap_btn_clear": "清空输出",
    "nmap_profile_default": "默认",
    "nmap_profile_fast": "快速（前 100 端口）",
    "nmap_profile_full": "全 TCP（1–65535）",
    "nmap_profile_intense": "深度（OS + 服务 + 脚本）",
    "nmap_profile_custom": "自定义参数",
    "nmap_profile_label": "当前方案",
    "nmap_chip_os": "OS 检测",
    "nmap_chip_services": "服务",
    "nmap_chip_fast": "快速",
    "nmap_chip_pn": "无 Ping",
    "nmap_chip_scripts": "NSE 脚本",
    "nmap_chip_aggressive": "激进",
    "nmap_chip_udp": "UDP",
    "nmap_chip_verbose": "详细",
    "nmap_status_idle": "空闲",
    "nmap_status_running": "运行中",
    "nmap_status_done": "完成",
    "nmap_status_stopped": "已停止",
    "nmap_status_error": "错误",
    "nmap_metric_lines": "行数",
    "nmap_metric_ports": "端口",
    "nmap_metric_hosts": "存活主机",
    "nmap_metric_time": "耗时",
    "nmap_output_placeholder": "# 输出将显示在这里…",
    "nmap_saved_to": "已保存到 %1$s",
    "nmap_copied": "输出已复制",
    "nmap_cleared": "输出已清除",
    "nmap_share_subject": "Nmap 扫描：%1$s",
    "nmap_custom_dialog_title": "自定义参数",
    "nmap_custom_dialog_body": "原样传递给 nmap 的附加参数。",
    "nmap_custom_dialog_hint": "例如 -sS -p 22,80,443 -T4",
    "nmap_recent_empty": "暂无最近目标",
    "nmap_recent_clear_all": "清除历史",
    "hs_title": "握手包",
    "hs_subtitle": "捕获的 Wi-Fi 握手包，可用于离线破解。",
    "hs_section_storage": "存储",
    "hs_section_files": "捕获文件",
    "hs_status_count": "已捕获 %1$d 个",
    "hs_status_empty": "暂无捕获",
    "hs_storage_path": "/sdcard/Stryker/captured",
    "hs_meta_size": "大小",
    "hs_meta_cracked": "已破解",
    "hs_meta_total": "总数",
    "hs_empty_title": "从 Wi-Fi 界面捕获握手包",
    "hs_empty_body": "保存到 /sdcard/Stryker/captured 的文件会出现在这里，可用于离线破解和上传。",
    "hs_open_capture": "打开 Wi-Fi 扫描器",
    "hs_refresh": "刷新",
    "hs_action_brute": "用字典破解",
    "hs_action_upload": "上传到 OnlineHashCrack",
    "hs_action_share": "分享文件",
    "hs_action_rename": "重命名",
    "hs_action_delete": "删除",
    "hs_action_stop": "停止破解",
    "hs_action_open_folder": "打开文件夹",
    "hs_state_cracked": "已破解",
    "hs_state_brute": "破解中",
    "hs_state_upload": "上传中",
    "hs_state_idle": "就绪",
    "hs_progress_starting": "正在启动…",
    "hs_progress_label": "进度",
    "hs_eta_label": "预计剩余",
    "hs_upload_email_title": "接收结果的邮箱",
    "hs_upload_email_body": "OnlineHashCrack 会将破解的密码发送到此邮箱。",
    "hs_upload_email_hint": "you@example.com",
    "hs_delete_title": "删除捕获？",
    "hs_delete_body": "%1$s 将从磁盘上永久删除。",
    "hs_rename_title": "重命名捕获",
    "hs_rename_hint": "new-name.cap",
    "hs_wordlist_title": "选择字典",
    "hs_wordlist_empty": "将字典放入 /sdcard/Stryker/wordlists",
    "hs_password_label": "密码",
    "hs_password_copy": "复制密码",
    "hs_password_copied": "密码已复制",
    "hs_share_failed": "无法分享此捕获",

    "core_mgr_title": "核心管理器",
    "core_mgr_subtitle": "管理驱动工具集的 chroot 软件包和 Python 模块。",
    "core_mgr_section_source": "来源",
    "core_mgr_section_search": "搜索",
    "core_mgr_section_packages": "软件包",
    "core_mgr_source_apk": "APT（Debian）",
    "core_mgr_source_pip": "Python（pip）",
    "core_mgr_apk_short": "apt",
    "core_mgr_pip_short": "pip",
    "core_mgr_search_hint_apk": "搜索 Debian 软件包",
    "core_mgr_search_hint_pip": "安装 Python 软件包",
    "core_mgr_status_loading": "正在加载…",
    "core_mgr_status_updating": "apt update…",
    "core_mgr_status_ready": "就绪",
    "core_mgr_status_count": "已安装 %1$d 个",
    "core_mgr_status_results": "%1$d 个结果",
    "core_mgr_empty_title": "未找到软件包",
    "core_mgr_empty_body": "尝试其他关键字或切换来源。",
    "core_mgr_pip_search_unavailable": "不支持 Python 搜索——请输入要安装的准确包名。",
    "core_mgr_installing": "正在安装 %1$s…",
    "core_mgr_uninstalling": "正在移除 %1$s…",
    "core_mgr_install_ok": "%1$s 已安装",
    "core_mgr_install_failed": "安装 %1$s 失败",
    "core_mgr_uninstall_ok": "%1$s 已移除",
    "core_mgr_uninstall_failed": "移除 %1$s 失败",
    "core_mgr_refresh": "刷新列表",
    "core_mgr_update_index": "apt update",
    "core_mgr_action_install": "安装",
    "core_mgr_action_uninstall": "卸载",
    "core_mgr_chip_installed": "已安装",
    "core_mgr_chip_python": "PIP",
    "core_mgr_chip_apk": "APT",
    "core_mgr_filter_all": "全部",
    "core_mgr_filter_installed": "已安装",
    "install_notif_channel": "工具安装",
    "install_notif_title": "正在安装 %1$s",
    "install_notif_starting": "正在启动…",
    "install_notif_running": "正在后台安装 %1$s",
    "install_notif_done": "%1$s 已安装",
    "install_notif_failed": "%1$s 安装失败",
    "tools_section_title": "已安装工具",
    "core_mgr_tool_searchsploit": "SearchSploit",
    "tools_section_subtitle": "重型 chroot 工具——安装将在后台运行",
    "tools_state_installed": "已安装",
    "tools_state_not_installed": "未安装",
    "tools_state_installing": "正在安装…",
    "tools_delete": "移除",
    "tools_delete_confirm_title": "移除 %1$s？",
    "tools_delete_confirm_message": "这将从 chroot 中删除 %1$s 及其文件。之后你可以重新安装。",
    "tools_delete_progress": "正在移除 %1$s…",
    "tools_delete_ok": "%1$s 已移除",
    "tools_delete_failed": "无法完全移除 %1$s",
    "msf_title": "Metasploit",
    "msf_subtitle_loading": "正在启动 RPC 控制台…",
    "msf_subtitle_ready": "搜索模块并发起攻击",
    "msf_subtitle_offline": "框架离线——点击重启",
    "msf_subtitle_install": "框架未安装",
    "msf_version_label": "v%1$s",
    "msf_section_status": "状态",
    "msf_section_modules": "模块",
    "msf_section_quick": "快捷操作",
    "msf_status_pill_online": "在线",
    "msf_status_pill_loading": "启动中",
    "msf_status_pill_offline": "离线",
    "msf_metric_exploits": "漏洞利用",
    "msf_metric_aux": "辅助",
    "msf_metric_sessions": "会话",
    "msf_search_hint": "搜索漏洞利用、辅助…",
    "msf_filter_all": "全部",
    "msf_filter_exploits": "漏洞利用",
    "msf_filter_aux": "辅助",
    "msf_filter_excellent": "仅优秀",
    "msf_action_restart": "重启 RPC",
    "msf_action_payload": "生成载荷",
    "msf_action_sessions": "打开会话",
    "msf_action_console": "原始控制台",
    "msf_chip_exploit": "漏洞利用",
    "msf_chip_aux": "辅助",
    "msf_chip_post": "后渗透",
    "msf_chip_payload": "载荷",
    "msf_rank_excellent": "优秀",
    "msf_rank_great": "极佳",
    "msf_rank_good": "良好",
    "msf_rank_normal": "正常",
    "msf_rank_average": "一般",
    "msf_rank_low": "较低",
    "msf_rank_manual": "手动",
    "msf_empty_title": "没有匹配的模块",
    "msf_empty_body": "尝试其他关键字或放宽过滤条件。",
    "msf_loading_title": "正在启动 Metasploit RPC",
    "msf_loading_body": "首次运行通常需要 30–90 秒。",
    "msf_console_restart_toast": "正在重启 RPC 控制台…",
    "msf_console_ready_toast": "控制台已就绪",
    "msf_console_failed_toast": "控制台启动失败——查看日志",
    "msf_install_title": "安装 Metasploit",
    "msf_install_subtitle": "在 chroot 内下载、编译并配置 Metasploit 框架。建议使用稳定的网络。",
    "msf_install_card_title": "Metasploit 框架",
    "msf_install_card_status_idle": "准备安装",
    "msf_install_card_status_running": "正在后台安装——你可以离开此界面",
    "msf_install_card_status_done": "已安装——正在打开仪表盘",
    "msf_install_card_status_failed": "安装失败——点击重试",
    "msf_install_btn_start": "安装框架",
    "msf_install_btn_retry": "重试安装",
    "msf_install_btn_open": "打开 Metasploit",
    "msf_install_stages_header": "步骤",
    "msf_install_log_header": "实时日志",
    "msf_install_warn": "安装需下载约 600 MB 并编译原生 gem。它在后台运行——完成后你会收到通知。",
    "msf_stage_index": "刷新 apt 索引",
    "msf_stage_deps": "安装构建依赖",
    "msf_stage_clone": "克隆 metasploit-framework",
    "msf_stage_msfpc": "拉取 msfpc 辅助脚本",
    "msf_stage_link": "链接二进制文件",
    "msf_stage_bundler": "安装 bundler + nokogiri",
    "msf_stage_bundle": "bundle install（较慢）",
    "msf_stage_warm": "预热 msfconsole",
    "msf_stage_verify": "验证安装",
    "msf_install_done": "Metasploit 已就绪",
    "msf_values_title": "配置模块",
    "msf_values_subtitle": "启动前检查并填写必填选项。",
    "msf_values_loading": "正在从 RPC 获取选项…",
    "msf_values_section_required": "必填",
    "msf_values_section_optional": "可选",
    "msf_values_section_safety": "安全覆盖",
    "msf_values_required_chip": "必填",
    "msf_values_missing_required": "请先填写所有必填字段",
    "msf_values_back": "返回",
    "msf_values_launch": "启动",
    "msf_values_open_url": "打开参考文档",
    "msf_values_no_options": "此模块没有可配置的选项。",
    "msf_runner_title": "模块运行器",
    "msf_runner_subtitle_running": "正在运行模块…",
    "msf_runner_subtitle_idle": "实时 shell 输出",
    "msf_runner_subtitle_done": "模块已完成",
    "msf_runner_btn_run": "运行",
    "msf_runner_btn_check": "检查漏洞",
    "msf_runner_btn_jobs": "终止任务",
    "msf_runner_btn_sessions": "会话",
    "msf_runner_btn_back": "返回",
    "msf_runner_btn_edit": "编辑选项",
    "msf_runner_btn_clear": "清除",
    "msf_runner_btn_save": "保存日志",
    "msf_runner_btn_copy": "复制",
    "msf_runner_btn_share": "分享",
    "msf_runner_btn_fullscreen": "全屏",
    "msf_runner_section_module": "模块",
    "msf_runner_section_terminal": "控制台",
    "msf_runner_saved_to": "已保存到 %1$s",
    "msf_runner_copied": "控制台已复制",
    "msf_runner_killed": "后台任务已终止",
    "payload_title": "载荷生成器",
    "payload_subtitle": "使用 msfvenom + msfpc 生成 stager 并放入 Stryker/payloads。",
    "payload_section_preset": "预设",
    "payload_section_target": "目标",
    "payload_section_output": "输出",
    "payload_preset_windows": "Windows",
    "payload_preset_android": "Android APK",
    "payload_preset_linux": "Linux",
    "payload_preset_php": "PHP",
    "payload_preset_python": "Python",
    "payload_preset_custom": "自定义",
    "payload_hint_type": "载荷类型",
    "payload_hint_ip": "LHOST（你的 IP）",
    "payload_hint_port": "LPORT",
    "payload_hint_name": "文件名",
    "payload_btn_generate": "生成",
    "payload_btn_cancel": "取消",
    "payload_log_title": "构建日志",
    "payload_status_idle": "填写表单并点击生成",
    "payload_status_running": "正在生成载荷——请保持对话框打开",
    "payload_status_done": "已保存到 /sdcard/Stryker/payloads",
    "payload_status_failed": "构建失败——查看日志",
    "payload_invalid": "请先填写全部四个字段",
    "hydra_install_title": "HTC-Hydra",
    "hydra_install_subtitle": "多协议暴力破解器 · 从 Debian 仓库拉取到工具集中",
    "hydra_section_status": "状态",
    "hydra_section_stages": "步骤",
    "hydra_section_log": "实时日志",
    "hydra_status_card_title": "Hydra 运行时",
    "hydra_status_idle": "点击安装以将 hydra 部署到 chroot",
    "hydra_status_running": "正在安装…",
    "hydra_status_done": "就绪 · 可从本地网络中的任意主机启动",
    "hydra_status_failed": "安装失败——点击重试",
    "hydra_install_warn": "未经许可对服务进行暴力破解在大多数国家/地区是非法的。只能针对你拥有或已获得书面同意测试的系统。",
    "hydra_btn_install": "安装 hydra",
    "hydra_btn_retry": "重试",
    "hydra_btn_open": "打开本地网络",
    "hydra_install_stage_refresh": "刷新 apt 索引",
    "hydra_install_stage_install": "apt install hydra",
    "hydra_install_stage_verify": "验证二进制文件",
    "cameradar_install_title": "Cameradar",
    "cameradar_install_subtitle": "RTSP 摄像头发现与默认凭据扫描 · 来自 GitHub 的官方发布二进制",
    "cameradar_section_status": "状态",
    "cameradar_section_stages": "步骤",
    "cameradar_section_log": "实时日志",
    "cameradar_status_card_title": "Cameradar 运行时",
    "cameradar_status_idle": "点击安装以获取 cameradar 发布二进制",
    "cameradar_status_running": "正在安装…",
    "cameradar_status_done": "就绪 · 可从本地网络中的任意摄像头主机启动",
    "cameradar_status_failed": "安装失败——点击重试",
    "cameradar_install_warn": "探测非你所有的摄像头在大多数国家/地区是非法的。只能针对你拥有或已获得书面同意测试的设备。",
    "cameradar_btn_install": "安装 cameradar",
    "cameradar_btn_retry": "重试",
    "cameradar_btn_open": "打开本地网络",
    "cameradar_install_stage_refresh": "安装依赖",
    "cameradar_install_stage_download": "下载发布版本",
    "cameradar_install_stage_unpack": "解压二进制文件",
    "cameradar_install_stage_verify": "验证二进制文件",
    "hydra_dialog_title": "Hydra 暴力破解",
    "hydra_dialog_status_idle": "选择服务、目标和凭据 → 启动",
    "hydra_dialog_status_found": "找到凭据",
    "hydra_dialog_status_progress": "已尝试 %1$d / %2$d",
    "hydra_section_service": "服务",
    "hydra_section_target": "目标",
    "hydra_section_credentials": "凭据",
    "hydra_section_tuning": "调优",
    "hydra_svc_ssh": "SSH",
    "hydra_svc_ftp": "FTP",
    "hydra_svc_smb": "SMB",
    "hydra_svc_rdp": "RDP",
    "hydra_svc_mysql": "MySQL",
    "hydra_svc_postgres": "PostgreSQL",
    "hydra_svc_telnet": "Telnet",
    "hydra_svc_vnc": "VNC",
    "hydra_svc_custom": "自定义",
    "hydra_hint_service": "服务（例如 imap、mssql、snmp）",
    "hydra_hint_host": "主机 / IP",
    "hydra_hint_port": "端口",
    "hydra_mode_wordlists": "字典",
    "hydra_mode_single": "单组凭据",
    "hydra_hint_login_wordlist": "用户名字典",
    "hydra_hint_password_wordlist": "密码字典",
    "hydra_hint_single_login": "用户名",
    "hydra_hint_single_password": "密码",
    "hydra_threads_label": "并行任务数",
    "hydra_chip_verbose": "详细",
    "hydra_chip_first": "命中后停止",
    "hydra_btn_launch": "启动",
    "hydra_btn_stop": "停止",
    "hydra_btn_close": "关闭",
    "hydra_action_fullscreen": "全屏日志",
    "hydra_action_copy": "复制凭据",
    "hydra_validation_target": "请先设置服务和主机",
    "hydra_validation_creds": "请输入密码（或切换到字典）",
    "hydra_validation_wordlist": "请选择密码字典（将文件放入 /sdcard/Stryker/wordlists）",
    "hydra_toast_copied": "已复制到剪贴板",

    "geomac_title": "GeoMac",
    "geomac_subtitle_idle": "已查询、扫描和破解 AP 的地图",
    "geomac_subtitle_count": "地图上有 %1$d 个标记",
    "geomac_subtitle_lookup": "正在查询 %1$s…",
    "geomac_subtitle_no_match": "未返回坐标",
    "geomac_subtitle_found": "找到 %1$s——已在地图上居中",
    "geomac_search_hint": "BSSID",
    "geomac_chip_all": "全部",
    "geomac_chip_lookup": "查询",
    "geomac_chip_scan": "已扫描",
    "geomac_chip_cracked": "已破解",
    "geomac_chip_manual": "手动",
    "geomac_not_installed": "GeoMac 模块未安装——前往管理器下载",
    "geomac_no_pins_to_fit": "没有标记匹配当前过滤条件",
    "geomac_copied": "坐标已复制",
    "geomac_bg_active": "后台扫描",
    "geomac_export_title": "导出标记",
    "geomac_export_json": "JSON（可回导）",
    "geomac_export_kml": "KML（Google 地球）",
    "geomac_export_empty": "暂无可导出内容",
    "geomac_export_ok": "已保存到 %1$s",
    "geomac_export_failed": "导出失败：%1$s",
    "geomac_import_title": "导入标记",
    "geomac_import_empty": "在 %1$s 中未找到 .json 文件——请先放入一个",
    "geomac_import_ok": "已导入 %1$d 个新标记",
    "geomac_import_failed": "导入失败：%1$s",
    "geomac_clear_title": "清除所有标记？",
    "geomac_clear_message": "这将清空整个本地地图。如需保留请先导出。",
    "geomac_clear_yes": "清除",
    "geomac_pin_age": "%1$s 前最后出现",
    "geomac_pin_btn_copy": "复制",
    "geomac_pin_btn_delete": "删除",
    "settings_section_geo": "地理映射",
    "settings_geo_bg_title": "自动标记扫描到的 AP",
    "settings_geo_bg_subtitle": "每次 wifi 扫描后，将每个 BSSID 通过 geomac 二进制文件查询",
    "settings_geo_satellite_title": "卫星瓦片模式",
    "settings_geo_satellite_subtitle": "将地图背景切换为 USGS 卫星影像（更耗资源）",
    "settings_section_msf": "Metasploit",
    "settings_msf_autostart_title": "启动时运行",
    "settings_msf_autostart_subtitle": "Stryker 启动时启动 Metasploit 框架（占用额外内存）",
    "settings_msf_stop_title": "停止 Metasploit",
    "settings_msf_stop_subtitle": "终止正在运行的 msfconsole 进程以释放内存",
    "settings_msf_stop_toast": "正在停止 Metasploit…",
    "settings_msf_stop_not_running": "Metasploit 未在运行",
    "nuclei_install_title": "Nuclei 扫描器",
    "nuclei_install_subtitle": "在 chroot 内用 Go 构建 ProjectDiscovery 扫描器。",
    "nuclei_section_status": "状态",
    "nuclei_section_stages": "步骤",
    "nuclei_section_log": "实时日志",
    "nuclei_status_card_title": "Nuclei 工具包",
    "nuclei_status_idle": "点击安装以获取 Go 并构建 nuclei（Wi-Fi 下约 3 分钟）。",
    "nuclei_status_running": "正在安装 nuclei…",
    "nuclei_status_done": "就绪——nuclei 已安装。",
    "nuclei_btn_install": "安装",
    "nuclei_btn_retry": "重试",
    "nuclei_btn_open": "打开扫描器",
    "nuclei_install_warn": "拉取最新的 arm64 签名 nuclei 发布版本（约 20 MB）。请保持屏幕常亮直到验证成功。",
    "nuclei_install_stage_prepare": "准备安装环境",
    "nuclei_install_stage_refresh": "刷新 apt 索引",
    "nuclei_install_stage_install_go": "解析最新发布版本",
    "nuclei_install_stage_go_build": "下载 arm64 二进制文件",
    "nuclei_install_stage_deploy": "部署 nuclei 到 /usr/bin",
    "nuclei_install_stage_templates": "获取模板库（需要几分钟）",
    "vm_required_terminal": "终端需要虚拟机——请先从仪表盘启动它",
    "engine_not_chosen": "尚未设置",
    "wifi_attack_custom_pin": "自定义 PIN",
    "wifi_attack_null_pin": "空 PIN",
    "wifi_attack_null_pin_hint": "空 WPS PIN",
    "wifi_null_pin_running": "正在尝试空 PIN——部分路由器接受空的 WPS PIN 并直接交出密钥。",
    "wifi_wps_locked_result": "此路由器已锁定 WPS。在解锁之前它会拒绝所有 PIN，通常需要重启或等待几分钟到几小时。",
    "wifi_foreign_owner_result": "另一个 Wi-Fi 管理器正在使用该适配器并中断了交换。这是干扰，不是对路由器的结论。",
    "wifi_no_driver_title": "适配器驱动缺失",
    "wifi_no_driver_subtitle": "已连接，但没有驱动",
    "wifi_no_driver_body": "适配器已到达虚拟机，但没有驱动接管它——10 秒内未出现 wlan 接口。\n\n打开终端为此芯片组安装驱动或固件，然后点击重试。",
    "local_netcut_no_l2_title": "Netcut 需要局域网访问",
    "local_netcut_no_l2_body": "Netcut 通过 ARP 欺骗工作，需要访问目标网络的二层。\n\n在无 root 模式下，虚拟机位于用户态 NAT（10.0.2.x）之后，ARP 帧永远无法到达真实局域网。实际上什么也不会被切断。\n\n要在此使用它，请将透传的 USB Wi-Fi 适配器以托管模式连接到目标网络，或切换到 root 引擎。",
    "nuclei_install_stage_verify": "验证 nuclei -version",
    "nuclei_main_title": "Nuclei",
    "nuclei_main_subtitle": "由 ProjectDiscovery 模板驱动的 Web 漏洞扫描器。",
    "nuclei_empty_title": "暂无目标",
    "nuclei_empty_subtitle": "点击“新建扫描”加入 URL——结果将显示在这里。",
    "nuclei_fab_new": "新建扫描",
    "nuclei_dialog_title": "新目标",
    "nuclei_dialog_url_hint": "URL 或主机",
    "nuclei_dialog_severity": "最低严重级别",
    "nuclei_dialog_start": "开始扫描",
    "nuclei_dialog_cancel": "取消",
    "nuclei_filter_all": "全部",
    "nuclei_filter_running": "运行中",
    "nuclei_filter_done": "已完成",
    "nuclei_filter_failed": "失败",
    "nuclei_stat_total": "目标",
    "nuclei_stat_findings": "发现",
    "nuclei_stat_running": "运行中",
    "nuclei_action_open": "打开报告",
    "nuclei_action_share": "分享",
    "nuclei_action_copy": "复制 URL",
    "nuclei_action_rescan": "重新扫描",
    "nuclei_action_stop": "停止扫描",
    "nuclei_action_remove": "移除",
    "nuclei_severity_info": "信息",
    "nuclei_severity_low": "低",
    "nuclei_severity_medium": "中",
    "nuclei_severity_high": "高",
    "nuclei_severity_critical": "严重",
    "nuclei_notif_channel": "Nuclei 扫描",
    "nuclei_notif_running": "正在扫描 %1$s",
    "nuclei_notif_done": "%1$s —— 扫描完成",
    "nuclei_notif_failed": "%1$s —— 扫描失败",
    "nuclei_status_scheduled": "已排队",
    "nuclei_status_progress": "运行中 · %1$s%%",
    "nuclei_status_finished": "已完成",
    "nuclei_status_failed": "失败",
    "tap_to_set_ranges": "点击设置 IP 范围",
    "tap_to_set_ports": "点击设置端口",
    "wpair_title": "WhisperPair",
    "wpair_subtitle": "CVE-2025-36911 扫描器 · BLE Fast Pair 渗透测试工具包",
    "wpair_stat_total": "发现",
    "wpair_stat_vulnerable": "存在漏洞",
    "wpair_stat_paired": "已配对",
    "wpair_filter_fastpair": "Fast Pair",
    "wpair_filter_all_ble": "全部 BLE",
    "wpair_filter_vulnerable": "存在漏洞",
    "wpair_filter_paired": "已配对",
    "wpair_section_devices": "设备",
    "wpair_terminal": "终端",
    "wpair_clear": "清除",
    "wpair_fab_scan": "扫描",
    "wpair_fab_stop": "停止扫描",
    "wpair_empty_title": "暂无设备",
    "wpair_empty_subtitle": "点击扫描以发现附近的 Fast Pair / BLE 设备",
    "wpair_badge_pairing": "配对中",
    "wpair_btn_test": "测试",
    "wpair_btn_magic": "魔法",
    "wpair_btn_more": "更多",
    "wpair_btn_write_key": "写入密钥",
    "wpair_btn_flood": "洪泛",
    "wpair_btn_hfp": "连接音频（HFP）",
    "wpair_btn_live": "实时",
    "wpair_btn_record": "录制",
    "wpair_btn_stop": "停止",
    "wpair_btn_terminal_filtered": "打开终端（已过滤）",
    "wpair_btn_close": "关闭",
    "wpair_dlg_idle": "空闲。请选择上方操作。",
    "wpair_dlg_section_exploit": "漏洞利用链",
    "wpair_dlg_section_audio": "音频访问",
    "wpair_dlg_section_tools": "工具",
    "wpair_terminal_title": "wpair 终端",
    "wpair_terminal_empty": "暂无输出——开始扫描或运行漏洞利用",
    "wpair_recordings_title": "录音",
    "wpair_recordings_refresh": "刷新",
    "wpair_recordings_empty_title": "暂无录音",
    "wpair_recordings_empty_subtitle": "成功的 HFP 捕获会以 M4A 格式存储在这里。",
    "wpair_disclaimer_title": "仅限授权测试",
    "wpair_disclaimer_msg": "WhisperPair 演示了一个允许访问麦克风的严重 BLE 漏洞。只能测试你拥有或获得书面许可的设备。未经授权使用属违法行为。",
    "wpair_disclaimer_accept": "我理解",
    "wpair_perm_title": "需要权限",
    "wpair_perm_msg": "WhisperPair 需要蓝牙、位置（旧版 BLE）和麦克风访问权限。",
    "wpair_perm_open_settings": "打开设置",
    "wpair_bt_disabled_title": "蓝牙已禁用",
    "wpair_bt_disabled_msg": "启用蓝牙以扫描附近的 Fast Pair 设备。",
    "wpair_bt_enable": "启用",
    "wpair_hfp_manual_title": "需要手动连接 HFP",
    "wpair_hfp_manual_msg": "Android 阻止程序化 HFP 连接。请打开蓝牙设置手动连接此设备，然后返回进行实时/录制。",
    "wpair_hfp_open_bt_settings": "打开蓝牙设置",
    "wpair_status_not_tested": "未测试",
    "wpair_status_testing": "测试中…",
    "wpair_status_vulnerable": "存在漏洞",
    "wpair_status_patched": "已修复",
    "wpair_status_error": "错误",
    "wpair_status_paired": "已配对",

    "about_tagline": "面向授权测试的免费开源移动渗透测试套件。",
    "about_pill_oss": "开源",
    "about_pill_root": "Root 驱动",
    "about_pill_pentest": "渗透测试套件",
    "about_feature_swipe_hint": "滑动",
    "feat_wifi_title": "WiFi 工具包",
    "feat_wifi_desc": "扫描附近网络、映射信道并捕获 WPA 握手包以供离线分析。",
    "feat_lan_title": "本地网络",
    "feat_lan_desc": "发现局域网主机并运行深度 Nmap 端口与服务扫描。",
    "feat_msf_title": "Metasploit",
    "feat_msf_desc": "在手机上直接驱动精选模块的 Metasploit 框架。",
    "feat_nuclei_title": "Nuclei 扫描器",
    "feat_nuclei_desc": "使用数千个社区模板大规模搜寻 Web 漏洞。",
    "feat_searchsploit_title": "SearchSploit",
    "feat_searchsploit_desc": "搜索离线 Exploit-DB 档案并转向开箱即用的 PoC。",
    "feat_hid_title": "HID 攻击",
    "feat_hid_desc": "将设备变成键盘，使用本地化键位触发 Ducky 载荷。",
    "about_section_links": "官方链接",
    "about_section_legal": "法律",
    "about_link_site_label": "项目网站",
    "about_link_github_label": "源代码",
    "about_oss_licenses_label": "开源许可证",
    "license_subtitle": "Stryker 基于以下开源项目构建。点击任意条目打开其源码。",
    "about_footer": "StrykerOSS —— 自由软件（GNU GPL v3.0）—— 仅限授权测试",
    "shortcut_terminal_short": "终端",
    "shortcut_terminal_long": "打开 Stryker 终端",
    "mac_title": "MAC 修改器",
    "mac_subtitle": "伪装或恢复任意无线接口的硬件地址。",
    "mac_iface_sub_idle": "点击接口下拉框切换",
    "mac_iface_hint": "接口",
    "mac_input_hint": "新 MAC 地址",
    "mac_section_form": "伪装",
    "mac_current_label": "当前 MAC",
    "mac_permanent_label": "永久 MAC",
    "mac_pill_idle": "空闲",
    "mac_pill_changing": "修改中…",
    "mac_pill_changed": "已修改",
    "mac_pill_reset": "已恢复",
    "mac_pill_error": "错误",
    "mac_pill_waiting_net": "等待网络",
    "mac_copy_desc": "复制 MAC 到剪贴板",
    "mac_copied_toast": "MAC 已复制到剪贴板",
    "mac_chip_random": "随机",
    "mac_chip_apple": "Apple OUI",
    "mac_chip_intel": "Intel OUI",
    "mac_chip_samsung": "Samsung OUI",
    "mac_chip_huawei": "Huawei OUI",
    "mac_btn_change": "应用 MAC",
    "mac_btn_reset": "恢复永久 MAC",
    "mac_invalid_format": "MAC 格式必须为 aa:bb:cc:dd:ee:ff",
    "mac_success": "MAC 地址已修改",
    "mac_failed": "修改 MAC 地址失败",
    "mac_waiting_net": "正在重新关联网络…",
    "mac_waiting_timeout": "网络重新关联耗时超过预期",
    "mac_get_permanent_failed": "无法读取永久 MAC",
    "mac_tip_general": "MAC 地址是唯一的链路层标识符。本地管理位使其在本地局域网上无冲突——请保持字节 0 的第二个半字节为 2/6/A/E。",
    "mac_tip_android12": "Android 12+ 在连接时会随机化并重新绑定 MAC。伪装后，内核可能会在下次握手时还原。请使用 MACsposed Xposed 模块实现永久覆盖。",
    "hid_title": "HID 攻击",
    "hid_subtitle": "通过 USB gadget 注入按键。仅限授权测试。",
    "hid_state_label": "Gadget 状态",
    "hid_state_unknown": "正在探测内核…",
    "hid_state_ready": "就绪 · 键盘已绑定",
    "hid_state_root_denied": "root 访问被拒绝",
    "hid_state_kernel_old": "内核太旧（需要 ≥ 3.19）",
    "hid_state_no_configfs": "configfs 不可用",
    "hid_state_no_udc": "没有 USB 设备控制器",
    "hid_state_no_node": "/dev/hidg0 缺失——请在 USB 武器库中应用 HID 配置",
    "hid_state_selinux": "SELinux 拒绝 hidraw 写入",
    "hid_layout_label": "键盘布局",
    "hid_layout_pick": "选择布局",
    "hid_editor_hint": "在此编写 DuckyScript——STRING、DELAY、GUI r、ENTER…",
    "hid_run": "运行",
    "hid_stop": "停止",
    "hid_load": "加载",
    "hid_save": "保存",
    "hid_clear": "清除",
    "hid_payload_library": "载荷库",
    "hid_payload_picker_title": "选择载荷",
    "hid_log_header": "执行日志",
    "hid_log_idle": "日志为空",
    "hid_save_dialog_title": "保存载荷",
    "hid_save_dialog_hint": "payload-name",
    "hid_save_ok": "载荷已保存",
    "hid_save_failed": "无法保存载荷",
    "hid_parse_error": "第 %1$d 行解析错误：%2$s",
    "hid_run_capability": "%s —— 打开 USB 武器库修复",
    "hid_progress_step": "第 %1$d / %2$d 行 · %3$s",
    "hid_progress_done": "%d 步完成",
    "hid_progress_cancelled": "运行已取消",
    "hid_progress_io_error": "I/O 错误：%s",
    "hid_editor_status_empty": "编辑器为空",
    "hid_editor_status_ready": "就绪 · %d 步%s",
    "screen_mirror_stats": "%1$.1f fps · %2$.1f KB/帧 · 总计 %3$s · 最近延迟 %4$d ms",
    "hid_editor_status_error": "第 %d 行出错",
    "hid_editor_lines": "%d 行",
    "hid_import": "导入",
    "hid_export": "导出",
    "hid_library": "库",
    "hid_export_ok": "载荷已导出",
    "hid_export_failed": "导出失败",
    "hid_import_failed": "无法读取文件",
    "hid_save_to_library": "保存到库",
    "hid_payload_actions": "载荷操作",
    "hid_payload_rename": "重命名",
    "hid_payload_delete": "删除",
    "hid_payload_move_up": "上移",
    "hid_payload_move_down": "下移",
    "hid_payload_rename_title": "重命名载荷",
    "hid_payload_delete_confirm": "从库中删除 \"%s\"？",
    "hid_payload_delete_hidden_note": "内置示例可通过“重置隐藏”找回。",
    "hid_payload_renamed": "已重命名为 \"%s\"",
    "hid_payload_deleted": "已从库中移除",
    "hid_payload_rename_failed": "重命名失败",
    "hid_files_title": "HID 攻击",
    "hid_files_subtitle": "浏览、编辑和运行 DuckyScript 载荷。仅限授权测试。",
    "hid_files_new": "新建脚本",
    "hid_files_open_arsenal": "打开 USB 武器库",
    "hid_files_filter_hint": "过滤载荷…",
    "hid_files_empty": "没有载荷。点击 + 编写一个。",
    "hid_files_section_samples": "内置示例",
    "hid_files_section_saved": "我的库",
    "ide_console": "控制台",
    "ide_caps_title": "能力",
    "ide_caps_recheck": "重新检查",
    "ide_caps_open_arsenal": "打开 USB 武器库",
    "ide_rename": "重命名文件",
    "ide_unsaved": "有未保存的更改——丢弃？",
    "ide_discard": "丢弃",
    "ide_keep_editing": "继续编辑",
    "ide_default_filename": "untitled.ducky",
    "ide_meta": "%1$d 行 · 列 %2$d",
    "ide_capture_title": "从主机捕获",
    "ide_capture_received": "第 %1$d 行 · 捕获：%2$s",
    "ide_capture_timeout": "第 %d 行 · GETWINHI 超时",
    "screen_mirror_title": "屏幕镜像",
    "screen_mirror_subtitle": "通过 CDC ACM 实时镜像主机屏幕。在电脑上运行 stryker-screen.ps1，然后点击此处开始。",
    "screen_mirror_start": "开始",
    "screen_mirror_stop": "停止",
    "screen_mirror_waiting": "正在等待第一帧…",
    "screen_mirror_no_node": "/dev/ttyGS0 缺失——请在 USB 武器库中应用 ACM 配置",
    "screen_mirror_no_root": "root 被拒绝",
    "screen_mirror_open_arsenal": "打开 USB 武器库",
    "screen_mirror_fullscreen_hint": "点击图像切换全屏",
    "screen_mirror_reap_label": "读取器交接延迟（毫秒）",
    "screen_mirror_reap_apply": "应用",
    "screen_mirror_reap_hint": "0 = 关闭 · 默认 50 · 若重开崩溃则调高",
    "screen_mirror_reap_saved": "Reap 稳定 = %d ms",
    "viewer_keyboard_toggle": "切换键盘",
    "viewer_keyboard_failed": "无法打开 /dev/hidg0——请在 USB 武器库中应用 HID 配置",
    "viewer_mouse_toggle": "切换鼠标模式",
    "viewer_mouse_failed": "无法打开 /dev/hidg1——请在 USB 武器库中应用 HID-to-Go 配置",

    "arsenal_usb_title": "USB 武器库",
    "arsenal_usb_subtitle": "构建并应用 USB gadget 配置。所选配置绑定到设备控制器，并向主机暴露所选功能。",
    "arsenal_state_label": "Gadget 状态",
    "arsenal_state_idle": "空闲 · 厂商 gadget 已绑定",
    "arsenal_state_bound": "已绑定到 %s",
    "arsenal_state_detached": "已分离——无控制器",
    "arsenal_profiles_label": "配置",
    "arsenal_apply": "应用",
    "arsenal_restore": "恢复厂商",
    "arsenal_new_profile": "新建配置",
    "arsenal_edit_profile": "编辑配置",
    "arsenal_delete_profile": "删除",
    "arsenal_reset_defaults": "恢复默认",
    "arsenal_field_name": "配置名称",
    "arsenal_field_target_os": "目标操作系统",
    "arsenal_field_vid": "USB 厂商 ID（0xVVVV）",
    "arsenal_field_pid": "USB 产品 ID（0xPPPP）",
    "arsenal_field_manufacturer": "制造商",
    "arsenal_field_product": "产品",
    "arsenal_field_serial": "序列号",
    "arsenal_functions_label": "功能",
    "arsenal_function_hid_kbd": "HID 键盘",
    "arsenal_function_hid_mouse": "HID 鼠标",
    "arsenal_function_mass": "大容量存储",
    "arsenal_function_rndis": "RNDIS",
    "arsenal_function_ecm": "ECM",
    "arsenal_function_acm": "串口（ACM）",
    "arsenal_function_adb": "ADB",
    "arsenal_mass_label": "大容量存储镜像",
    "arsenal_mass_pick": "选择 .img / .iso",
    "arsenal_mass_readonly": "只读",
    "arsenal_mass_cdrom": "模拟 CD-ROM",
    "arsenal_mass_inquiry": "查询字符串（28 个 ASCII）",
    "arsenal_apply_ok": "配置已应用——gadget 已绑定到 %s",
    "arsenal_apply_failed": "应用配置失败（查看 logcat）",
    "arsenal_restore_ok": "厂商 gadget 已恢复",
    "arsenal_save": "保存",
    "arsenal_cancel": "取消",
    "arsenal_vid_invalid": "VID 格式应为 0x046d",
    "arsenal_pid_invalid": "PID 格式应为 0xc31c",
    "arsenal_select_function": "至少需要一个功能",
    "arsenal_no_capability": "内核 / 设备无法承载 USB gadget——详情请查看 HID 界面",
    "delete_app_confirm_cta": "删除所有内容",
    "delete_app_item_chroot": "•  Chroot 环境与所有已安装工具",
    "delete_app_item_data": "•  应用数据、设置与已保存结果",
    "delete_app_item_app": "•  Stryker 本身",
    "delete_app_removing": "正在移除 Stryker…",
    "delete_app_step_unmount": "正在卸载环境",
    "delete_app_step_wipe": "正在清除 /data/local/stryker",
    "delete_app_step_uninstall": "正在卸载应用",
    "delete_app_fail": "无法卸载——请关闭所有使用 chroot 的程序后重试",
    "delete_app_close": "关闭",
    "logs_title": "日志",
    "logs_loading": "正在加载…",
    "logs_count": "%1$s 条记录",
    "logs_count_filtered": "%1$s 条记录（已过滤）",
    "logs_clear": "清除日志",
    "logs_save": "保存日志",
    "logs_share": "分享日志",
    "logs_search_hint": "过滤日志…",
    "logs_search_clear": "清除搜索",
    "logs_level_cmd": "命令",
    "logs_level_out": "输出",
    "logs_level_err": "错误",
    "logs_level_info": "信息",
    "logs_tool_all": "所有工具",
    "logs_empty": "没有日志记录匹配你的过滤条件。",
    "logs_cleared": "日志已清除。",
    "logs_saved": "已保存到 %1$s",
    "logs_save_failed": "无法导出日志。",
    "settings_section_engine": "引擎",
    "settings_vm_title": "虚拟机",
    "settings_vm_subtitle": "磁盘、CPU、内存与速度调优",
    "vm_title": "虚拟机",
    "vm_subtitle": "给虚拟机更多空间并根据你的手机调优。",
    "vm_device_title": "此设备",
    "vm_section_resources": "资源",
    "vm_disk_title": "磁盘大小",
    "vm_disk_subtitle": "为工具提供更多空间",
    "vm_disk_dialog_title": "虚拟机磁盘大小",
    "vm_disk_grow_confirm": "扩展到 %1$d GB。这将停止虚拟机、调整磁盘大小然后重新启动。继续？",
    "vm_disk_growing": "正在调整磁盘大小…",
    "vm_disk_grown": "磁盘已扩展到 %1$d GB——文件系统将在启动时扩展。",
    "vm_disk_grow_failed": "无法调整磁盘大小：%1$s",
    "vm_cpu_title": "CPU 核心数",
    "vm_cpu_subtitle": "虚拟处理器",
    "vm_cpu_dialog_title": "vCPU 核心数",
    "vm_ram_title": "内存",
    "vm_ram_subtitle": "分配给虚拟机的 RAM",
    "vm_ram_dialog_title": "虚拟机内存（MB）",
    "vm_section_autotune": "自动调优",
    "vm_recommend_title": "使用推荐配置",
    "vm_recommend_applied": "已应用推荐配置。",
    "vm_benchmark_title": "运行基准测试",
    "vm_benchmark_subtitle": "测试配置，选择最快的",
    "vm_benchmark_running": "基准测试中…",
    "vm_benchmark_reboot_warn": "基准测试会多次重启虚拟机以计时每个配置。大约需要一两分钟。现在运行吗？",
    "vm_benchmark_done": "最佳：%1$d vCPU · %2$d MB",
    "vm_benchmark_failed": "基准测试失败：%1$s",
    "vm_section_experiments": "实验",
    "vm_experiments_warn": "速度调整。有些以安全换取速度——如果虚拟机无法启动，请将它们关闭。",
    "vm_cache_title": "磁盘缓存模式",
    "vm_cache_subtitle": "unsafe = 最快，崩溃时有数据风险",
    "vm_cache_dialog_title": "磁盘缓存模式",
    "vm_aio_title": "异步 I/O",
    "vm_aio_subtitle": "io_uring 可能更快",
    "vm_aio_dialog_title": "异步 I/O 后端",
    "vm_mttcg_title": "多线程 TCG",
    "vm_mttcg_subtitle": "KVM 关闭时使用所有核心",
    "vm_norng_title": "禁用 virtio-rng",
    "vm_norng_subtitle": "跳过 RNG 设备",
    "vm_noshare_title": "禁用文件共享",
    "vm_noshare_subtitle": "不将 /sdcard 共享进虚拟机",
    "vm_pauth_title": "指针认证（PAC）",
    "vm_pauth_subtitle": "关闭可让 PAC 操作码免费——最大的 TCG 收益",
    "vm_pauth_dialog_title": "客户机指针认证",
    "vm_pauth_off": "off——不通告（最快）",
    "vm_pauth_impdef": "impdef——快速 QEMU 哈希",
    "vm_pauth_qarma": "qarma——架构化，非常慢",
    "vm_iothread_title": "磁盘 I/O 线程",
    "vm_iothread_subtitle": "让 virtio-blk 远离主循环",
    "vm_fastboot_title": "客户机快速启动命令行",
    "vm_fastboot_subtitle": "在虚拟机中移除 init_on_alloc、audit 和 KASLR",
    "vm_apply_restart": "应用并重启虚拟机",
    "vm_apply_hint": "CPU、内存和实验更改将在下次虚拟机启动时生效。",
    "vm_restarting": "正在重启虚拟机…",
    "vm_kvm": "KVM",
    "vm_tcg": "TCG",
    "vm_boot_title": "正在启动 Linux 虚拟机",
    "vm_boot_stage_start": "正在启动模拟器…",
    "vm_boot_stage_kernel": "内核正在启动…",
    "vm_boot_stage_rootfs": "正在挂载根文件系统…",
    "vm_boot_stage_services": "正在启动客户机服务…",
    "vm_boot_stage_agent": "正在等待客户机代理…",
    "vm_boot_stage_ready": "客户机已启动",
    "vm_boot_stage_failed": "虚拟机未能启动",
    "vm_boot_cpu": "CPU",
    "vm_boot_ram": "RAM",
    "vm_boot_dash": "—",
    "vm_boot_log_header": "启动日志",
    "vm_boot_retry": "重试",
    "vm_boot_continue": "仍然继续",
    "vm_boot_back_blocked": "引擎仍在启动…",
    "vm_boot_pid": "pid %1$d",
    "vm_boot_stage_restart": "正在停止正在运行的虚拟机…",
    "vm_boot_safe_profile": "已使用安全配置启动——实验功能已禁用",
    "vm_boot_fallback_retry": "首次启动失败——正在使用安全配置重试…",
    "intro_step_of": "步骤 %1$d/%2$d",
    "intro_step_placeholder": "步骤 1/1",
    "vm_section_stats": "统计",
    "vm_section_usb": "USB",
    "vm_section_logs": "控制台",
    "vm_usb_none": "无",
    "vm_usb_attached_to_vm": "已附加到虚拟机",
    "vm_usb_host_only": "在手机上",
    "vm_stats_offline": "虚拟机已停止",
    "vm_stats_blocked": "此 ROM 不可读",
    "vm_stats_waiting": "收集中…",
    "vm_stats_range_span": "最近 %1$s · 5 秒采样 · 保留 24 小时",
    "vm_stats_range_empty": "暂无样本",
    "vm_stats_peak": "峰值 %1$d MB",
    "vm_aio_probing": "正在检查 QEMU 是否支持 io_uring…",
    "vm_aio_unsupported": "此处不支持 io_uring（%1$s）——继续使用线程",
    "vm_aio_supported": "io_uring 已验证——应用并重启以使用",
    "vm_aio_sub_verified": "已验证",
    "vm_aio_sub_unsupported": "此设备不支持",
    "vm_aio_sub_untested": "尚未测试",
    "vm_disk_restart_hint": "正在扩展磁盘…",
    "vm_safe_boot_title": "安全配置",
    "vm_safe_boot_subtitle": "启动失败后启用；禁用时清除",
    "vm_stats_cpu": "虚拟机 CPU",
    "vm_stats_ram": "虚拟机 RAM",
    "vm_boot_elapsed": "%1$02d:%2$02d",
    "local_location_rationale": "位置权限让 Stryker 读取 Wi-Fi BSSID，以便在扫描中显示路由器 MAC 和厂商。",
    "vm_stat_cpu": "CPU 负载",
    "vm_stat_ram": "内存",
    "vm_stat_placeholder": "—",
    # ---- strings_news.xml ----
    "news_read_more": "阅读更多",
    "news_no_app": "没有已安装的应用可以打开此链接。",
    # ---- strings_ota.xml ----
    "ota_channel_name": "更新与新闻",
    "ota_update_available_title": "有可用更新",
    "ota_update_available_body": "版本 %1$s 可用。点击更新。",
    "ota_dialog_title": "有可用更新",
    "ota_dialog_body": "Stryker %1$s 可用。",
    "ota_dialog_update": "更新",
    "ota_dialog_later": "稍后",
    "ota_dialog_skip": "跳过此版本",
    "ota_downloading": "正在下载更新…",
    "ota_download_failed": "更新下载失败",
    "ota_enable_unknown_sources": "允许从 Stryker 安装应用以继续更新",
    # ---- strings_promo.xml ----
    "promo_github_title": "喜欢 Stryker 吗？",
    "promo_github_message": "Stryker 是免费开源软件。如果它对你有用，在 GitHub 上点个星有助于项目发展并触达更多人。",
    "promo_github_action": "在 GitHub 上点星",
    "promo_blog_title": "保持关注",
    "promo_blog_message": "新工具、文章和版本说明会首先发布在博客上。看看接下来会有什么。",
    "promo_blog_action": "访问博客",
    "promo_later": "稍后再说",
    # ---- strings_wifi.xml ----
    "wifi_monitor_failed": "无法在 %1$s 上启用监控模式。\n\n可能的原因：\n• 适配器或其芯片组不支持监控模式（大多数内置的非高通 Wi-Fi 芯片不支持）。\n• 适配器未被检测到或被拔出。\n• 接口忙或已关闭，或驱动以不同名称暴露它。\n\n解决方法：\n• 设置 → 网络接口：为握手/deauth 选择其他适配器。\n• 重新插入外部 USB Wi-Fi 适配器，然后重新扫描。\n• 使用支持监控模式的适配器（例如 Atheros AR9271、Realtek RTL8812AU / 88XXAU）。\n• 设置 → 自定义监控命令：调整你的适配器启用监控模式的方式。\n• 确保 Android Wi-Fi / 热点没有占用接口——将其关闭后重试。",

    # ---- Drawer navigation (MainActivity 资源化) ----
    "menu_dashboard": "仪表盘",
    "menu_terminal": "终端",
    "menu_logs": "日志",
    "menu_wifi": "WiFi 网络",
    "menu_handshakes": "握手包",
    "menu_mac_changer": "MAC 修改器",
    "menu_wpair": "WhisperPair (BLE)",
    "menu_local_network": "本地网络",
    "menu_nmap": "Nmap",
    "menu_web_scanner": "Web 扫描器",
    "menu_arsenal": "武器库",
    "menu_hid": "HID 攻击",
    "menu_metasploit": "Metasploit",
    "menu_geomac": "GeoMac",
    "menu_vnc": "VNC 桌面",
    "menu_usb_arsenal": "USB 武器库",
    "menu_core_manager": "核心管理器",
    "menu_about": "关于",
    "needs_root_hardware": "%1$s 需要 root 硬件——在无 root 虚拟机上不可用",
    "needs_vm": "%1$s 需要虚拟机——请先从仪表盘启动",
    "this_tool": "此工具",
    "drawer_section_essentials": "常用",
    "drawer_section_wireless": "无线",
    "drawer_section_network": "网络",
    "drawer_section_offensive": "进攻",
    "drawer_section_tools": "工具",
    "drawer_chroot_mounted": "Chroot 已挂载",
    "drawer_chroot_unmounted": "Chroot 未挂载",

    # ---- Dialog titles (Java 硬编码资源化) ----
    "title_news": "新闻",
    "title_confirmation": "确认",
    "title_permission_denied": "权限被拒绝",
    "title_geomac": "GeoMac",
    "title_select_exploit": "选择漏洞利用",
    "title_mac_change_failed": "修改 MAC 地址失败。",
    "title_vnc_installer": "VNC 安装器",
    "title_uninstall_vnc": "卸载 VNC？",
    "title_pmkid_capture": "PMKID 捕获",
    "title_wps_locked": "WPS 已锁定",
    "title_additional_info": "附加信息",
    "title_select_pin": "选择 PIN",
    "title_delete_recording": "删除录音？",
    "drawer_rootless_note": "需要使用手机自带的无线/USB gadget——在无 root 虚拟机上不可用",
    "drawer_footer": "开源 · 仅限授权测试",
}
