# -*- coding: utf-8 -*-
"""
zh_dict_terminal.py — terminal 模块（Stryker 内置终端）简体中文词典
格式: name -> 中文文案。占位符（%s, %d, %1$s, \\n 等）必须与英文原文一致。
SKIP: 原样保留的 key（如超长许可证法律文本，不翻译以保持法律效力）。
"""
# flake8: noqa
TRANSLATIONS = {
    "copy_text": "复制",
    "paste_text": "粘贴",
    "super_paste_text": "超级粘贴",
    "text_selection_more": "更多",
    "toggle_tab_switcher_menu_item": "切换标签页",
    "new_session": "新建会话",
    "new_session_more": "新建会话…",
    "new_system_session": "新建系统 Shell",
    "new_root_session": "新建 Root Shell",
    "service_status_text": "%d 个会话",
    "service_lock_acquired": "（已持有唤醒锁）",
    "service_acquire_lock": "获取唤醒锁",
    "service_release_lock": "释放唤醒锁",
    "setup_info": "你好，Stryker 终端",
    "setup_next": "开始吧！",
    "setup_setup_method": "选择安装方式",
    "setup_online": "在线安装",
    "setup_local": "本地压缩包安装",
    "setup_backup": "从 Stryker 终端备份恢复",
    "setup_source_parameter": "源参数",
    "setup_input_source_parameter": "输入源参数…",
    "setup_hint_online": "包含安装压缩包的镜像 URL",
    "setup_hint_local": "压缩包文件路径",
    "setup_hint_backup": "备份文件路径（*.neobackup）",
    "setup_error_file_not_found": "文件未找到",
    "setup_error_invalid_url": "URL 无效",
    "setup_error_no_internet": "无网络连接",
    "setup_error_connection_failed": "连接服务器失败",
    "setup_error_parameter_null": "安装参数为空",
    "setup_preparing": "正在准备…",
    "setup_confirm": "完成安装",
    "setup_confirm_text": "到目前为止一切正常，继续吗？",
    "setup_reset_confirm": "确认重置",
    "setup_reset_confirm_text": "此操作将清除你的所有数据！继续？",
    "about": "关于",
    "settings": "设置",
    "general_settings": "常规设置",
    "general_settings_desc": "铃声、Shell、初始命令",
    "ui_settings": "界面设置",
    "ui_settings_desc": "全屏、标题栏、动画",
    "package_settings": "软件包设置",
    "package_settings_desc": "源、更新、升级",
    "customization_settings_desc": "字体、配色方案",
    "customization_settings": "个性化",
    "term_settings_subtitle": "Stryker 终端",
    "term_settings_section_prefs": "偏好",
    "term_settings_section_maint": "维护",
    "term_settings_section_about": "关于",
    "term_settings_general_title": "常规",
    "term_settings_general_subtitle": "初始命令、按键与输入",
    "term_settings_ui_title": "界面",
    "term_settings_ui_subtitle": "全屏、工具栏、标签页、附加按键",
    "term_settings_customization_title": "个性化",
    "term_settings_customization_subtitle": "字体与配色方案",
    "term_settings_reset_title": "重置终端资源",
    "term_settings_reset_subtitle": "重新解压内置 Shell 脚本",
    "term_settings_licenses_title": "开源许可证",
    "term_settings_licenses_subtitle": "第三方组件",
    "term_settings_github_title": "GitHub 项目",
    "term_settings_github_subtitle": "github.com/zalexdev/strykerapp",
    "term_pref_initial_command_title": "初始命令",
    "term_pref_initial_command_subtitle": "在每个新会话中自动运行",
    "term_pref_initial_command_hint": "例如 neofetch",
    "term_pref_backspace_esc_title": "返回键发送 ESC",
    "term_pref_backspace_esc_subtitle": "将设备返回键映射为 Escape",
    "term_pref_volume_ctrl_title": "音量键作为 Ctrl",
    "term_pref_volume_ctrl_subtitle": "音量减作为 Ctrl 修饰键",
    "term_pref_word_ime_title": "基于词的输入",
    "term_pref_word_ime_subtitle": "更友好的输入法建议，精确度较低",
    "term_pref_fullscreen_title": "全屏",
    "term_pref_fullscreen_subtitle": "隐藏系统状态栏",
    "term_pref_hide_toolbar_title": "自动隐藏工具栏",
    "term_pref_hide_toolbar_subtitle": "输入时隐藏工具栏",
    "term_pref_next_tab_title": "关闭时跳转到下一个标签页",
    "term_pref_next_tab_subtitle": "会话关闭后向前切换",
    "term_pref_eks_title": "附加按键行",
    "term_pref_eks_subtitle": "在键盘上方显示 Ctrl / Esc / 方向键",
    "term_pref_eks_weight_title": "附加按键等距",
    "term_pref_eks_weight_subtitle": "均匀分布附加按键",
    "term_settings_value_none": "无",
    "term_dialog_save": "保存",
    "toggle_ime": "切换键盘",
    "float_up": "浮动",
    "shell_not_found": "未找到 Shell %s",
    "shell_not_found_message": "是否要安装它？",
    "fullscreen_mode_changed": "全屏模式已更改，请重启 Stryker 终端。",
    "permission_denied": "存储权限被拒绝——外部文件访问受限（终端仍可正常使用）。",
    "error": "哎呀！",
    "use_system_shell": "系统 Shell",
    "retry": "重试",
    "source_changed": "APT 源已更改，可执行 apt update 获取更新",
    "done": "完成",
    "install": "安装",
    "package_details": "软件包：%s\n版本：%s\n依赖：%s\n安装大小：%s\n描述：%s\n主页：%s",
    "package_list_empty": "软件包列表为空，请检查你的源。",
    "menu_refresh_list": "刷新",
    "menu_update": "更新并刷新",
    "install_font": "安装字体",
    "install_color": "安装配色方案",
    "crash_model": "机型：%s",
    "crash_app": "应用：%s",
    "crash_stack_trace": "堆栈跟踪",
    "installer_message": "正在安装",
    "installer_install_zsh_required": "我们将安装 oh-my-zsh 并把登录程序切换为 zsh",
    "pref_general_bell": "铃声",
    "pref_general_bell_desc": "收到 '\\a' 时响铃",
    "pref_general_backspace_map_to_esc": "退格键映射为 Esc",
    "pref_general_backspace_map_to_esc_desc": "按退格键时发送 esc",
    "pref_general_shell": "登录程序",
    "pref_general_shell_desc": "登录时使用哪个程序作为 shell",
    "pref_general_initial_command": "初始命令",
    "pref_general_initial_command_desc": "创建会话时执行的命令",
    "pref_general_auto_completion": "自动补全（实验性）",
    "pref_general_auto_completion_desc": "输入命令或路径时启用补全。此功能仍在开发中，存在大量 bug",
    "pref_general_volume_as_control": "使用音量上下键作为特殊按键",
    "pref_general_volume_as_control_desc": "音量减作为 Ctrl\n音量加作为 FN",
    "pref_general_use_execve_wrapper": "使用 execve() 包装器",
    "pref_general_use_execve_wrapper_desc": "钩住 execve() 以避免错误的 shebang",
    "pref_general_enable_word_based_ime": "启用基于词的输入法",
    "pref_general_enable_word_based_ime_desc": "基于词或基于字符的输入法",
    "pref_ui_fullscreen": "全屏",
    "pref_ui_hide_toolbar": "隐藏工具栏",
    "pref_ui_hide_toolbar_desc": "键盘显示时隐藏工具栏",
    "pref_ui_close_tab_anim_next_tab": "下一个标签页动画",
    "pref_ui_close_tab_anim_next_tab_desc": "关闭标签页时切换到下一个标签页而不是上一个",
    "pref_ui_eks_weight_explicit": "为附加按键使用显式权重",
    "pref_ui_eks_weight_explicit_desc": "如果附加按键显示异常，请启用此项",
    "pref_ui_eks_enabled": "显示附加按键",
    "pref_ui_eks_enabled_desc": "一些有用的按键，如方向键、esc、tab 等",
    "pref_customization_font": "字体",
    "pref_customization_color_scheme": "配色方案",
    "pref_customization_eks": "附加按键",
    "pref_package_source": "源",
    "exit": "退出",
    "term_here": "在此打开终端",
    "user_script": "用户脚本",
    "command_shortcut": "命令快捷方式",
    "no_user_script_found": "未找到用户脚本（是否忘记设置可执行权限？）",
    "no_files_selected": "未选择文件\n\n（原始 Intent: %s）",
    "unsupported_term_here": "此处不支持打开终端\n\n（原始 Intent: %s）",
    "files_to_handle": "待处理文件",
    "available_user_scripts": "可用用户脚本",
    "confirm_remove_file_from_list": "从列表中移除文件？",
    "confirm_remove": "移除？",
    "command_shortcut_display_title": "标题",
    "command_shortcut_command": "命令",
    "no_command_extra": "未提供命令，是否忘了添加 extras？",
    "command_display_title_cannot_be_null": "显示标题不能为空",
    "menu_upgrade": "升级",
    "apt_update_ok": "软件包列表更新成功",
    "apt_upgrade_ok": "软件包升级成功",
    "installing_topic": "安装已开始。请注意屏幕上出现的提示",
    "session_closed": "会话已关闭",
    "restore_session": "取消",
    "show_help": "显示帮助",
    "service_connection_failed": "连接服务失败",
    "about_version_label": "版本",
    "about_developers_label": "开发者与贡献者",
    "about_libraries_label": "库",
    "about_source_label": "源代码",
    "about_reset_label": "重置应用",
    "about_reset_label_desc": "清除除用户主目录外的所有文件",
    "new_color_scheme": "新建配色方案",
    "faq": "常见问题",
    "new_source": "新建",
    "process_exit_info": "进程已结束",
    "process_exit_code": "退出码 %d",
    "process_exit_signal": "信号 %d",
    "process_exit_prompt": "按回车",
    "process_exit_prompt_press_back": "按返回键",
    "save_color_info": "输入新的配色方案名称",
    "save_color_scheme_name_template": "NewColorScheme",
    "save_color": "保存配色方案",
    "discard_changes": "放弃所有更改？",
    "save": "保存",
    "select_new_value": "选择",
    "input_new_value": "输入新颜色",
    "toggle_eks": "切换附加按键",
    "new_x_session": "新建 X 会话",
    "new_session_with_profile": "使用配置新建会话",
    "no_profile_available": "没有可用配置",
    "no_file_picker": "未找到文件选择器",
    "input_new_source_url": "输入新 URL",
    "input_new_source_repo": "输入新仓库",
    "error_new_source_url": "URL 不能为空",
    "error_new_source_repo": "仓库不能为空",
    "dangerous_zone": "危险区域",
    "reset_app_warning": "这将删除并重新复制启动 Stryker chroot 所需的文件，确认？",
    "source_code": "源代码许可证",
    "title_activity_theme_creator": "主题创建器",
    "version": "版本：",
    "support_us": "支持我们",
    "developers": "开发者",
    "get_usb_devices": "获取 USB 设备",
    "get_interfaces": "获取接口",
    "tools": "工具",
    "term_wifi_dialog_title": "无线接口",
    "term_wifi_scanning": "正在扫描适配器…",
    "term_wifi_empty": "未检测到无线接口",
    "term_wifi_count": "检测到 %1$d 个适配器",
    "term_iface_type_monitor": "监控",
    "term_iface_type_managed": "托管",
    "term_monitor_enable": "启用监控",
    "term_monitor_disable": "停止监控",
    "term_monitor_working": "工作中…",
    "term_usb_dialog_title": "USB 设备",
    "term_usb_scanning": "正在枚举 USB…",
    "term_usb_empty": "没有已连接的 USB 设备",
    "term_usb_count": "已连接 %1$d 个设备",
    "term_dialog_refresh": "刷新",
    "term_dialog_close": "关闭",
    "term_op_timeout": "操作超时——点击刷新重试",
}

# 超长许可证法律文本：保留英文原文（法律文本不翻译以保持效力）
SKIP = {"sources_licenses"}
