# -*- coding: utf-8 -*-
"""
zh_dict_xorg.py — Xorg/SDL 模块（内置 VNC/模拟器配置界面）简体中文词典
"""
# flake8: noqa
TRANSLATIONS = {
    "init": "正在初始化",
    "please_wait": "正在下载数据，请稍候",
    "device_config": "设备配置",
    "device_change_cfg": "更改设备配置",
    "download_unneeded": "无需下载",
    "connecting_to": "正在连接到 %s",
    "failed_connecting_to": "连接 %s 失败",
    "error_connecting_to": "连接 %s 出错",
    "dl_from": "正在从 %s 下载数据",
    "error_dl_from": "从 %s 下载数据出错",
    "error_write": "写入 %s 出错",
    "dl_progress": "%1$.0f%% 完成：文件 %2$s",
    "dl_finished": "完成",
    "storage_phone": "内部存储 - 剩余 %d MB",
    "storage_sd": "SD 卡存储 - 剩余 %d MB",
    "storage_custom": "指定目录",
    "storage_commandline": "命令行参数，每行一个参数",
    "storage_question": "数据安装位置",
    "optional_downloads": "下载",
    "downloads": "下载",
    "ok": "确定",
    "cancel": "取消",
    "controls_arrows": "方向键 / 摇杆 / 十字键",
    "controls_trackball": "轨迹球",
    "controls_accel": "加速度传感器",
    "controls_touch": "仅触摸屏",
    "controls_question": "你的设备有哪些导航键？",
    "controls_additional": "附加控制",
    "controls_screenkb": "屏幕键盘",
    "controls_accelnav": "加速度传感器",
    "controls_screenkb_size": "屏幕键盘大小",
    "controls_screenkb_drawsize": "按钮图像大小",
    "controls_screenkb_large": "大",
    "controls_screenkb_medium": "中",
    "controls_screenkb_small": "小",
    "controls_screenkb_tiny": "极小",
    "controls_screenkb_custom": "自定义",
    "controls_screenkb_theme": "屏幕键盘主题",
    "controls_screenkb_by": "%1$s 由 %2$s 制作",
    "controls_screenkb_transparency": "屏幕键盘透明度",
    "controls_screenkb_trans_0": "不可见",
    "controls_screenkb_trans_1": "几乎不可见",
    "controls_screenkb_trans_2": "透明",
    "controls_screenkb_trans_3": "半透明",
    "controls_screenkb_trans_4": "不透明",
    "trackball_no_dampening": "无阻尼",
    "trackball_fast": "快",
    "trackball_medium": "中",
    "trackball_slow": "慢",
    "trackball_question": "轨迹球阻尼",
    "accel_veryfast": "非常快",
    "accel_fast": "快",
    "accel_medium": "中",
    "accel_slow": "慢",
    "accel_veryslow": "非常慢",
    "accel_question": "加速度传感器灵敏度",
    "accel_floating": "浮动",
    "accel_fixed_start": "应用启动时固定",
    "accel_fixed_horiz": "固定为桌面方向",
    "accel_question_center": "加速度传感器中心位置",
    "mouse_emulation": "鼠标模拟",
    "rightclick_question": "鼠标右键",
    "rightclick_menu": "菜单键",
    "rightclick_key": "物理按键",
    "rightclick_multitouch": "第二根手指触摸屏幕",
    "rightclick_pressure": "用力触摸屏幕",
    "rightclick_none": "禁用鼠标右键",
    "leftclick_question": "鼠标左键",
    "leftclick_normal": "正常",
    "leftclick_near_cursor": "在鼠标光标附近触摸",
    "leftclick_multitouch": "第二根手指触摸屏幕",
    "leftclick_pressure": "用力触摸屏幕",
    "leftclick_dpadcenter": "轨迹球点击 / 摇杆中心",
    "leftclick_timeout": "在相同位置按住",
    "leftclick_tap": "轻点",
    "leftclick_tap_or_timeout": "轻点或按住",
    "leftclick_timeout_time": "按住超时",
    "leftclick_timeout_time_0": "0.3 秒",
    "leftclick_timeout_time_1": "0.5 秒",
    "leftclick_timeout_time_2": "0.7 秒",
    "leftclick_timeout_time_3": "1 秒",
    "leftclick_timeout_time_4": "1.5 秒",
    "click_with_dpadcenter": "用轨迹球 / 摇杆中心左键点击",
    "advanced": "高级功能",
    "mouse_keepaspectratio": "保持 4:3 屏幕纵横比",
    "mouse_showcreenunderfinger": "在独立窗口中显示手指下的屏幕",
    "mouse_showcreenunderfinger2": "屏幕放大镜",
    "mouse_joystickmouse": "用摇杆或轨迹球移动鼠标",
    "mouse_joystickmousespeed": "用摇杆移动鼠标的速度",
    "mouse_joystickmouseaccel": "用摇杆移动鼠标的加速度",
    "mouse_relative": "相对鼠标移动（笔记本模式）",
    "mouse_relative_speed": "相对鼠标移动速度",
    "mouse_relative_accel": "相对鼠标移动加速度",
    "mouse_hover_jitter_filter": "过滤触控笔/手指悬停抖动",
    "mouse_gyroscope_mouse": "用陀螺仪控制鼠标",
    "mouse_gyroscope_mouse_sensitivity": "陀螺仪灵敏度",
    "mouse_finger_hover": "手指悬停",
    "mouse_subframe_touch_events": "每视频帧多个触摸事件",
    "none": "无",
    "measurepressure": "校准触摸屏压力",
    "measurepressure_touchplease": "请在屏幕上滑动手指两秒钟",
    "measurepressure_response": "压力 %1$03d 半径 %2$03d",
    "audiobuf_verysmall": "非常小（快速设备，延迟更低）",
    "audiobuf_small": "小",
    "audiobuf_medium": "中",
    "audiobuf_large": "大（旧设备，声音卡顿时使用）",
    "audiobuf_question": "音频缓冲区大小",
    "remap_hwkeys": "重映射物理按键",
    "remap_hwkeys_press": "按除 HOME 和 POWER 外的任意按键，可使用音量键",
    "remap_hwkeys_select": "选择 SDL 键码",
    "remap_hwkeys_select_simple": "选择操作",
    "remap_hwkeys_select_more_keys": "显示所有键码",
    "remap_screenkb": "重映射屏幕控制",
    "remap_screenkb_joystick": "摇杆",
    "remap_screenkb_button": "按钮",
    "remap_screenkb_button_text": "文本输入按钮",
    "remap_screenkb_button_gestures": "双指手势",
    "remap_screenkb_button_gestures_sensitivity": "双指手势灵敏度",
    "remap_screenkb_button_zoomin": "双指放大手势",
    "remap_screenkb_button_zoomout": "双指缩小手势",
    "remap_screenkb_button_rotateleft": "双指向左旋转手势",
    "remap_screenkb_button_rotateright": "双指向右旋转手势",
    "screenkb_custom_layout": "自定义屏幕键盘布局",
    "screenkb_custom_layout_help": "完成后按返回键。在空白处滑动可调整按钮大小。",
    "screenkb_floating_joystick": "浮动摇杆",
    "calibrate_touchscreen": "校准触摸屏",
    "calibrate_touchscreen_touch": "触摸屏幕所有边缘，完成后按返回键",
    "video": "视频设置",
    "video_smooth": "线性视频过滤",
    "video_separatethread": "视频使用独立线程，可提高 FPS，也可能导致崩溃",
    "video_orientation_vertical": "竖屏方向",
    "video_orientation_autodetect": "自动检测屏幕方向",
    "video_bpp_24": "24 bpp 屏幕色深",
    "video_immersive": "隐藏系统导航按钮 / 沉浸模式",
    "tv_borders": "电视边框",
    "text_edit_click_here": "点击开始输入，完成后按返回键",
    "display_size_mouse": "鼠标模拟模式",
    "display_size": "鼠标模拟的显示大小",
    "display_size_desktop": "桌面，无模拟",
    "display_size_large": "大（平板）",
    "display_size_small": "小，放大镜",
    "display_size_small_touchpad": "小，触摸板模式",
    "display_size_tiny": "极小",
    "display_size_tiny_touchpad": "极小，触摸板模式",
    "show_more_options": "显示更多选项",
    "hardware_mouse_detected": "检测到硬件鼠标，正在禁用鼠标模拟",
    "not_enough_ram": "内存不足",
    "not_enough_ram_size": "此应用需要 %1$d MB 内存，你的设备有 %2$d MB",
    "ignore": "忽略",
    "calibrate_gyroscope": "校准陀螺仪",
    "calibrate_gyroscope_text": "将设备放在平坦的表面上",
    "calibrate_gyroscope_not_supported": "你的设备没有陀螺仪",
    "reset_config": "将配置重置为默认值",
    "reset_config_ask": "将所有选项重置为默认值？",
    "cancel_download": "取消数据下载？",
    "cancel_download_resume": "你可以稍后继续，数据不会被重复下载。",
    "yes": "是",
    "no": "否",
    "gamehelper_sign_in_failed": "登录失败。请检查网络连接后重试。",
    "gamehelper_app_misconfigured": "应用配置错误。请检查包名和签名证书是否与开发者控制台中创建的客户端 ID 匹配。另外，如果应用尚未发布，请检查你尝试登录的账户是否列为测试账户。更多信息请查看日志。",
    "gamehelper_license_failed": "许可证检查失败。",
    "gamehelper_unknown_error": "未知错误。",
    "accessing_network": "正在访问网络，请稍候",
    "restarting_please_wait": "正在重启，请稍候。",
    "notification_app_is_running": "%s 正在运行",
    "notification_stop": "停止",
}
